/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'igor' at '4/27/14 4:27 PM' with Gradle 1.9
 *
 * @author igor, @date 4/27/14 4:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
